-- Migración: tabla inventory_listings
-- Ejecutar en Supabase SQL Editor o via psql.
-- Requiere que existan: users, games, cards, card_variants (creadas por sync).
-- El juego se obtiene por JOIN: variant_id → card_variants → cards → games.

CREATE TABLE IF NOT EXISTS public.inventory_listings (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id   bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    variant_id  bigint NOT NULL REFERENCES public.card_variants(id) ON DELETE CASCADE,
    quantity    int NOT NULL DEFAULT 1 CHECK (quantity > 0),
    price_usd   numeric NOT NULL CHECK (price_usd > 0),
    price_cop   numeric NOT NULL DEFAULT 0,
    status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'sold', 'inactive')),
    language    text NOT NULL DEFAULT 'Inglés',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_inventory_listings_seller ON public.inventory_listings (seller_id);
CREATE INDEX IF NOT EXISTS idx_inventory_listings_variant ON public.inventory_listings (variant_id);
CREATE INDEX IF NOT EXISTS idx_inventory_listings_status ON public.inventory_listings (status);
