// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/cards/import": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Importar cartas seleccionadas de búsquedas",
                "parameters": [
                    {
                        "description": "Grupos por búsqueda: search_id devuelto + IDs elegidos",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "groups": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "external_ids": {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            },
                                            "search_id": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "cards": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/catalog.Card"
                                    }
                                },
                                "imported": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin/cards/import-listing": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Importar cartas y publicarlas al inventario",
                "parameters": [
                    {
                        "description": "Grupos por búsqueda con los datos de publicación",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "groups": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "items": {
                                                "type": "array",
                                                "items": {
                                                    "type": "object",
                                                    "properties": {
                                                        "external_id": {
                                                            "type": "string"
                                                        },
                                                        "language": {
                                                            "type": "string"
                                                        },
                                                        "price_usd": {
                                                            "type": "number"
                                                        },
                                                        "quantity": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            },
                                            "search_id": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "imported": {
                                    "type": "integer"
                                },
                                "listings": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/catalog.ImportedListing"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin/pokemon/expansions/sync": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Sincronizar expansiones Pokémon",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "synced": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Iniciar sesión",
                "parameters": [
                    {
                        "description": "Credenciales",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "token": {
                                    "type": "string"
                                },
                                "user": {
                                    "type": "object",
                                    "properties": {
                                        "email": {
                                            "type": "string"
                                        },
                                        "first_name": {
                                            "type": "string"
                                        },
                                        "id": {
                                            "type": "integer"
                                        },
                                        "last_name": {
                                            "type": "string"
                                        },
                                        "role": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Credenciales inválidas",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registrar usuario",
                "parameters": [
                    {
                        "description": "Datos del nuevo usuario",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "first_name": {
                                    "type": "string"
                                },
                                "last_name": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "token": {
                                    "type": "string"
                                },
                                "user": {
                                    "type": "object",
                                    "properties": {
                                        "email": {
                                            "type": "string"
                                        },
                                        "first_name": {
                                            "type": "string"
                                        },
                                        "id": {
                                            "type": "integer"
                                        },
                                        "last_name": {
                                            "type": "string"
                                        },
                                        "role": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Email ya registrado",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Datos de validación inválidos",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/catalog/cards": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Listar cartas del catálogo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código del juego (pokemon, mtg, riftbound)",
                        "name": "game_code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la expansión",
                        "name": "expansion_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nombre parcial de la carta",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Rareza exacta (ej: Rare Holo)",
                        "name": "rarity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tipo de carta (ej: Fire para Pokémon, Creature para Magic)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Página (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Resultados por página (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "cards": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/catalog.CardSummary"
                                    }
                                },
                                "page": {
                                    "type": "integer"
                                },
                                "page_size": {
                                    "type": "integer"
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/catalog/pokemon/expansions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokemon"
                ],
                "summary": "Listar expansiones Pokémon",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/catalog.Expansion"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/expansions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Listar expansiones",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del juego (opcional)",
                        "name": "game_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.expansionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/games": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Listar juegos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.gameResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/listings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "listings"
                ],
                "summary": "Listar listings",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Límite",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.listingResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "listings"
                ],
                "summary": "Crear listing",
                "parameters": [
                    {
                        "description": "Datos del listing",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createListingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.listingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/listings/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "listings"
                ],
                "summary": "Eliminar listing",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del listing",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "listings"
                ],
                "summary": "Actualizar cantidad de un listing",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del listing",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nueva cantidad (0 = inactivo)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "quantity": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.listingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/scrydex/magic/cards": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "magic"
                ],
                "summary": "Buscar cartas Magic",
                "parameters": [
                    {
                        "description": "Filtros (name es requerido)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "expansion_code": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "rarity": {
                                    "type": "string"
                                },
                                "type": {
                                    "type": "string"
                                },
                                "variants": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "cards": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/catalog.Card"
                                    }
                                },
                                "search_id": {
                                    "type": "string"
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/scrydex/pokemon/cards": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokemon"
                ],
                "summary": "Buscar cartas Pokémon",
                "parameters": [
                    {
                        "description": "Filtros de búsqueda (name es requerido)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "expansion_code": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "rarity": {
                                    "type": "string"
                                },
                                "supertype": {
                                    "type": "string"
                                },
                                "type": {
                                    "type": "string"
                                },
                                "variants": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "cards": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/catalog.Card"
                                    }
                                },
                                "search_id": {
                                    "type": "string"
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/scrydex/pokemon/cards/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokemon"
                ],
                "summary": "Obtener carta Pokémon por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la carta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Variantes",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "variants": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog.Card"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/scrydex/riftbound/cards": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riftbound"
                ],
                "summary": "Buscar cartas Riftbound",
                "parameters": [
                    {
                        "description": "Filtros (name es requerido)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "expansion_code": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "rarity": {
                                    "type": "string"
                                },
                                "type": {
                                    "type": "string"
                                },
                                "variants": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "cards": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/catalog.Card"
                                    }
                                },
                                "search_id": {
                                    "type": "string"
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/scrydex/riftbound/cards/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riftbound"
                ],
                "summary": "Obtener carta Riftbound por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la carta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Variantes",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "variants": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog.Card"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "catalog.Card": {
            "type": "object",
            "properties": {
                "abilities": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "artist": {
                    "type": "string"
                },
                "attacks": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "color_identity": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "colors": {
                    "description": "MTG",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "evolves_from": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "expansion": {
                    "$ref": "#/definitions/catalog.Expansion"
                },
                "expansion_sort_order": {
                    "type": "integer"
                },
                "external_id": {
                    "type": "string"
                },
                "faces": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "flavor_text": {
                    "type": "string"
                },
                "hp": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.Image"
                    }
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "layout": {
                    "type": "string"
                },
                "mana_cost": {
                    "type": "string"
                },
                "mana_value": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "national_pokedex_numbers": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "number": {
                    "type": "string"
                },
                "power": {
                    "type": "string"
                },
                "printed_number": {
                    "type": "string"
                },
                "rarity": {
                    "type": "string"
                },
                "rarity_code": {
                    "type": "string"
                },
                "resistances": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "retreat_cost": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rulings": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "subtypes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "supertype": {
                    "type": "string"
                },
                "toughness": {
                    "type": "string"
                },
                "type_line": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "variants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.Variant"
                    }
                },
                "weaknesses": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                }
            }
        },
        "catalog.CardSummary": {
            "type": "object",
            "properties": {
                "expansion": {
                    "$ref": "#/definitions/catalog.ExpansionBrief"
                },
                "external_id": {
                    "type": "string"
                },
                "game_code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "$ref": "#/definitions/catalog.ImageBrief"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "rarity": {
                    "type": "string"
                },
                "stock": {
                    "description": "Stock agregado de listings activos con cantidad \u003e 0. El catálogo\npúblico solo muestra cartas con stock disponible.",
                    "type": "integer"
                },
                "variants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.VariantBrief"
                    }
                }
            }
        },
        "catalog.Expansion": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "external_id": {
                    "type": "string"
                },
                "game_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "printed_total": {
                    "type": "integer"
                },
                "release_date": {
                    "type": "string"
                },
                "series": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "catalog.ExpansionBrief": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "symbol_url": {
                    "type": "string"
                }
            }
        },
        "catalog.Image": {
            "type": "object",
            "properties": {
                "large": {
                    "type": "string"
                },
                "medium": {
                    "type": "string"
                },
                "small": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "catalog.ImageBrief": {
            "type": "object",
            "properties": {
                "large": {
                    "type": "string"
                },
                "medium": {
                    "type": "string"
                },
                "small": {
                    "type": "string"
                }
            }
        },
        "catalog.ImportedListing": {
            "type": "object",
            "properties": {
                "card_name": {
                    "type": "string"
                },
                "external_id": {
                    "type": "string"
                },
                "game_code": {
                    "type": "string"
                },
                "listing_id": {
                    "type": "integer"
                },
                "merged": {
                    "type": "boolean"
                },
                "price_cop": {
                    "type": "number"
                },
                "price_usd": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "variant_name": {
                    "type": "string"
                }
            }
        },
        "catalog.Marketplace": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "purchase_url": {
                    "type": "string"
                }
            }
        },
        "catalog.Price": {
            "type": "object",
            "properties": {
                "low_cop": {
                    "type": "integer"
                },
                "low_usd": {
                    "type": "number"
                },
                "market_cop": {
                    "type": "integer"
                },
                "market_usd": {
                    "type": "number"
                },
                "trm_used": {
                    "type": "number"
                }
            }
        },
        "catalog.Variant": {
            "type": "object",
            "properties": {
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.Image"
                    }
                },
                "marketplaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.Marketplace"
                    }
                },
                "name": {
                    "type": "string"
                },
                "nm_price": {
                    "$ref": "#/definitions/catalog.Price"
                },
                "origin": {
                    "type": "string"
                }
            }
        },
        "catalog.VariantBrief": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "price_cop": {
                    "type": "integer"
                },
                "price_usd": {
                    "type": "number"
                }
            }
        },
        "http.createListingRequest": {
            "type": "object",
            "properties": {
                "language": {
                    "type": "string"
                },
                "price_usd": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "variant_id": {
                    "type": "integer"
                }
            }
        },
        "http.expansionResponse": {
            "type": "object",
            "properties": {
                "Code": {
                    "type": "string"
                },
                "ExternalID": {
                    "type": "string"
                },
                "GameID": {
                    "type": "integer"
                },
                "ID": {
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                },
                "ReleasedAt": {
                    "type": "string"
                }
            }
        },
        "http.gameResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "http.listingResponse": {
            "type": "object",
            "properties": {
                "CardImage": {
                    "type": "string"
                },
                "CardName": {
                    "type": "string"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "ExpansionName": {
                    "type": "string"
                },
                "GameName": {
                    "type": "string"
                },
                "ID": {
                    "type": "integer"
                },
                "Language": {
                    "type": "string"
                },
                "PriceCOP": {
                    "type": "number"
                },
                "PriceUSD": {
                    "type": "number"
                },
                "Quantity": {
                    "type": "integer"
                },
                "SellerID": {
                    "type": "integer"
                },
                "Status": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                },
                "VariantID": {
                    "type": "integer"
                },
                "VariantName": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Ingresá el token con el prefijo Bearer. Ej: \"Bearer eyJ...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Trample API",
	Description:      "API para el catálogo de cartas coleccionables.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
