-- Esquema real de la tabla `public.users` (Supabase / PostgreSQL)
--
-- IMPORTANTE: el repositorio del backend consulta la columna `password_hash`
-- (NO `password`). Cualquier migración que renombre columnas debe mantener esto
-- en sincronía con internal/adapters/out/postgres/user_repository_pg.go.
--
-- Para ver el esquema vivo:
--   SELECT column_name, data_type, is_nullable, column_default
--   FROM information_schema.columns
--   WHERE table_schema = 'public' AND table_name = 'users';

CREATE TABLE public.users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    first_name    text NOT NULL DEFAULT '',
    last_name     text NOT NULL DEFAULT '',
    role          text NOT NULL DEFAULT 'customer',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.games (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL
);

-- Juegos soportados por el catálogo (códigos usados por los endpoints /scrydex/{game}):
--   1 'pokemon'    'Pokémon TCG'
--   2 'mtg'        'Magic: The Gathering'
--   3 'riftbound'  'Riftbound'
-- INSERT INTO public.games (code, name) VALUES
--   ('pokemon', 'Pokémon TCG'),
--   ('mtg', 'Magic: The Gathering'),
--   ('riftbound', 'Riftbound')
-- ON CONFLICT (code) DO NOTHING;

-- Notas de seguridad
-- * `password_hash` guarda SOLO el hash bcrypt (golang.org/x/crypto/bcrypt).
--   Nunca guardar passwords en texto plano.
-- * El login compara el hash con bcrypt.CompareHashAndPassword.
-- * El rol "admin" se asigna manualmente en la DB (el register público siempre
--   crea usuarios con rol "customer", ver internal/domain/auth/user.go).
